name: Buildroot for Raspberry Pi 3

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential gcc make unzip wget bc libncurses-dev git python3 rsync

    - name: Clone Buildroot
      run: |
        git clone --depth 1 https://github.com/buildroot/buildroot.git

    - name: Apply defconfig and update config
      run: |
        cp configs/rpi3_desktop_defconfig buildroot/configs/
        cd buildroot
        make rpi3_desktop_defconfig
        make olddefconfig

    - name: Build Image
      run: |
        cd buildroot
        make

    - name: Upload output image
      uses: actions/upload-artifact@v4
      with:
        name: buildroot-rpi3-output
        path: buildroot/output/images/
