name: Buildroot for Raspberry Pi 3 – Desktop

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1) جلب الريبو
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2) الأدوات المطلوبة على Runner
    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential gcc make rsync wget unzip bc git \
          libncurses-dev python3

    # 3) جلب آخر نسخة من Buildroot (أو ثبّت فرع/تاج محدَّد لو حابب)
    - name: Clone Buildroot
      run: |
        git clone --depth 1 https://github.com/buildroot/buildroot.git

    # 4) تطبيق defconfig + تحديث الإعدادات القديمة
    - name: Configure Buildroot (defconfig + br2‑update‑config)
      working-directory: buildroot
      run: |
        # نستخدم الـ defconfig الموجود خارج شجرة Buildroot
        make BR2_DEFCONFIG=../configs/rpi3_desktop_defconfig defconfig
        # يحوّل أي خيارات قديمة للجديدة تلقائيًا
        make br2-update-config
        # يملأ القيم الافتراضية ويضمن عدم وجود أسئلة تفاعليّة
        make olddefconfig

    # 5) بناء الصورة
    - name: Build image
      working-directory: buildroot
      run: make -j"$(nproc)"

    # 6) رفع ناتج البناء
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: rpi3-desktop-image
        path: buildroot/output/images/
