name: Buildroot – RPi3 Desktop Image

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y sed make binutils gcc g++ bash patch \
          gzip bzip2 perl tar cpio python3 unzip rsync wget \
          libncurses5-dev libssl-dev bc file

    - name: Clone Buildroot
      run: |
        git clone --depth 1 https://github.com/buildroot/buildroot.git

    - name: Apply custom defconfig
      run: |
        cp configs/rpi3_desktop_defconfig buildroot/configs/
        cd buildroot
        make rpi3_desktop_defconfig

    - name: Build Buildroot image
      run: |
        cd buildroot
        make -j$(nproc)

    - name: Upload output
      uses: actions/upload-artifact@v4
      with:
        name: rpi3-desktop-image
        path: buildroot/output/images/
